[package]
name = "kageb-program"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
custom-heap = []
custom-panic = []
no-entrypoint = []

[lints]
workspace = true

[dependencies]
sha2 = { version = "=0.10.9", default-features = false }
solana-program = "=4.0.0"
solana-instructions-sysvar = "=3.0.0"
solana-sdk-ids = "=3.1.0"
solana-system-interface = { version = "=3.0.0", features = ["bincode"] }
solana-sysvar = "=4.0.0"
spl-token-interface = "=2.0.0"

[dev-dependencies]
solana-account = "=3.4.0"
solana-ed25519-program = "=3.0.0"
solana-keypair = "=3.1.0"
solana-program-test = { version = "=4.0.0", features = ["agave-unstable-api"] }
solana-signer = "=3.0.0"
solana-transaction = "=3.1.0"
solana-transaction-error = "=3.0.0"
tokio = { version = "=1.49.0", features = ["macros", "rt-multi-thread"] }
